### ISSUE TITLE
chronosynth installation issue when running Custom_synth_dating.ipynb

### ISSUE THREAD

**Issue by LunaSare** [OpenTreeOfLife/ChronoSynth#4]
Before running `dates = json.load(open("../node_ages1.json"))`

It reads

```
# From git@github.com:OpenTreeOfLife/ChronoSynth.git
# this file is generated by running examples/conflict_test_all.py
```

I understood that it was suggesting that you should run `examples/conflict_test_all.py`, especially because there is no "node_ages1.json"

So I tried installing chronosynth, generated a new venv ok, activated it ok, and when trying `pip install requirements.txt` I got:

```
ERROR: Could not find a version that satisfies the requirement requirements.txt
ERROR: No matching distribution found for requirements.txt
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode
```

Then I realized I could keep on running the example with the "node_ages.json" file instead of generating a "node_ages1.json". But now I wonder what's going on with the installation 😱 

Finally, I think a pointer to instructions to install phylocom should be really helpful too!

**Comment by snacktavish** [comment]
Ah! 
for the first issue it is because it needs 
```pip install -r requirements.txt```

**Comment by snacktavish** [comment]
But yes - I agree that install instructions which include the phylocom install are a very good idea!

**Comment by LunaSare** [comment]
using `-r` worked! MTH also suggested adding all dependencies into the `setup.py` as `install_requires`
